version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.15.3
    container_name: qdrant
    volumes:
      - /var/qdrant/storage:/qdrant/storage
    environment:
      TZ: Asia/Seoul
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
      QDRANT__STORAGE__ON_DISK: "true"
      QDRANT__STORAGE__DISABLE_FS_AVAILABILITY_CHECK: "true"
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
